// samples/angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { ComponentLibraryModule } from '@dubai-design-system/components-angular';

@Component({
  selector: 'app-root',
  imports: [ComponentLibraryModule],
  template: `
    <h1>DDA Angular sample</h1>
    <dda-button
      button_color="default-primary"
      start_icon="sentiment_satisfied"
      end_icon="arrow_forward"
      button_id="button"
      aria_label="button">
      Button
    </dda-button>
  `,
})
export class AppComponent {}

// samples/react/src/App.jsx
import { DdaButton } from '@dubai-design-system/components-react';

export default function App() {
  return (
    <div>
      <h1>DDA React sample</h1>
      <DdaButton
        button_color="default-primary"
        start_icon="sentiment_satisfied"
        end_icon="arrow_forward"
        button_id="button"
        aria_label="button"
      >
        Button
      </DdaButton>
    </div>
  );
}
